name: Java CI

on:
  push:
    branches:
      - main
      - entrega-intermediaria

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compilar projeto
      run: javac *.java

    - name: Rodar teste
      run: java CotacaoServiceTest